### ISSUE TITLE
Add ability to configure servers

### ISSUE THREAD

**Issue by dkleissa** [gigantum/gigantum-desktop#125]
## Description

Adding a new server to a locally installed client is to be handled by the Desktop App and CLI. The Desktop app should be updated to include a new button and modal for adding servers, along with the logic to properly discover a server and save its configuration.

## Tasks
- [ ] Update designs to add button and modal
- [ ] Implement updated designs
- [ ] Implement logic based on the Client implementation to check for a server, discover its configuration, and store a configuration for a new server.
