### ISSUE TITLE
When stopping on Windows, taskbar screen needs to be updated for WSL 2

### ISSUE THREAD

**Issue by dkleissa** [gigantum/gigantum-desktop#164]
## Description
When you stop the Client on windows the taskbar screen needs to be updated for WSL 2. Currently, it says "remember docker is still running, It is now safe to quit docker". The "show me how" button doesn't link to anything specific that shows you now. Also, on WSL 2 you don't need to worry about it.

## Tasks
- [ ] Make screen conditional on windows + hyperV and windows + wsl
- [ ] On wsl don't bother showing the screen
- [ ] On hyperv, fix the link
