### ISSUE TITLE
Prepare new app architecture

### ISSUE THREAD

**Issue by dkleissa** [gigantum/gigantum-desktop#37]
**Description**
As we move to the improved install process, we are going to significantly update the electron app architecture. This will make the software more reliable and easy to maintain going forward. To get this process started, the two projects need to be merged as a starting point

**Tasks**
- [x] Create branch, move over new app architecture, move existing code to temporary legacy folder
- [x] Clean out new architecture and setup initial state machine
- [ ] Configure build process and certs
- [ ] Setup sentry
