### ISSUE TITLE
Complete new app wireframes

### ISSUE THREAD

**Issue by dkleissa** [gigantum/gigantum-desktop#38]
**Description**
New app UI and structure has been wireframed to a point. This needs to be completed so dev can move as quickly as possible.

**Tasks**
- [ ] Combine install process with app screens
- [ ] Finalize dropdown layout 
- [ ] Build out all states for dropdown
- [ ] Design settings screen
