### ISSUE TITLE
Complete Windows Installer

### ISSUE THREAD

**Issue by dkleissa** [gigantum/gigantum-desktop#50]
The windows installer needs to be implemented with its unique screens and docker automation process.

**Tasks**
- [ ] Complete Installer process for windows
- [ ] Add docker automation for windows
- [ ] Create docker Install animation
