### ISSUE TITLE
Write and implement FAQs for installer

### ISSUE THREAD

**Issue by dkleissa** [gigantum/gigantum-desktop#51]
The installer has multiple sections where FAQs are available for the user to get additional information. The topics should be finalized, body written, and any additional docs pages created as needed.

**Tasks**
- [ ] Finalize topics
- [ ] Write body for all FAQs
- [ ] Generate any additional docs pages if needed
- [ ] Add FAQ content to installer
