### ISSUE TITLE
Implement Linux installer and tray location

### ISSUE THREAD

**Issue by dkleissa** [gigantum/gigantum-desktop#53]
The installer process for linux needs to be developed along with any adjustments required to make the tray location render properly.

**Tasks**
- [ ] Add docker install process on linux via the recommended script
- [ ] Skip the configure docker step on linux
- [ ] Verify the tray app renders properly
