### ISSUE TITLE
Complete remaining tray app screens

### ISSUE THREAD

**Issue by dkleissa** [gigantum/gigantum-desktop#54]
There are several screens yet to be implemented in the tray app that must be completed and tested

**Tasks**
- [ ] Auto-update screen
- [ ] Settings screen and logic
- [ ] About screen, including the release notes and acknowledgements screens
